version: "3.8"

x-disabled: &disabled # Define a common option to disable automatic restart
  restart: "no"

services:
  redis:
    image: redis:latest
    container_name: go-allocator-redis
    ports:
      - "63790:6379"
    <<: *disabled
    volumes:
      - go_allocator_redis_data:/data

volumes:
  go_allocator_redis_data:
